src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $body;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $created;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = trim($title);

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function getCreated(): ?string
    {
        return date('M j Y g:i:s a', strtotime($this->created));
    }

    public function setBody(string $body): self
    {
        $this->body = trim($body);

        return $this;
    }

    public function setCreated(string $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getUserId(): ?int
    {
        return (int)$this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, ['attr' => ['class' => 'form-control', 'maxlength' => 32]])
            ->add('body', TextAreaType::class,
                ['attr' => ['class' => 'form-control', 'cols' => 5, 'maxlength' =>255]]
            );

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Entity\User;
use App\Form\PostType;
use App\Repository\PostRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\HttpFoundation\Session\SessionInterface;

/**
 * @Route("/post")
 */
class PostController extends AbstractController
{
    protected $session;
    public function __construct(SessionInterface $session)
    {
        // must be logged in to view this controller
        $this->session = $session;
    }

    /**
     * @Route("/", name="post_index", methods={"GET"})
     */
    public function index(PostRepository $postRepository): Response
    {
        if($this->session->get('is_logged_in') == true){
            return $this->render('post/index.html.twig', ['posts' => $postRepository->findAll()]);
        } else {
            return $this->redirectToRoute('app_login');
        }
    }

    /**
     * @Route("/new", name="post_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        if($this->session->get('is_logged_in') == true)
        {
            $post = new Post();
            $form = $this->createForm(PostType::class, $post);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();

                // set user id
                $post->setUserId(intval($this->session->get('user_id')));
                $post->setCreated(date('Y-m-d H:i:s'));

                $entityManager->persist($post);
                $entityManager->flush();

                return $this->redirectToRoute('post_index');
            }

            return $this->render('post/new.html.twig', [
                'post' => $post,
                'form' => $form->createView(),
            ]);
        } else {
            return $this->redirectToRoute('app_login');
        }
    }

    /**
     * @Route("/{id}", name="post_show", methods={"GET"})
     */
    public function show(Post $post): Response
    {
        if($this->session->get('is_logged_in') == true) {
            return $this->render('post/show.html.twig', [
                'post' => $post,
            ]);
        } else {
            return $this->redirectToRoute('app_login');
        }
    }

    /**
     * @Route("/{id}/edit", name="post_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Post $post): Response
    {

        if($this->session->get('is_logged_in') == true) {

            // if user is logged in, lets test to see if user can edit
            if($this->session->get('user_id') == $post->getUserId()){
                $form = $this->createForm(PostType::class, $post);
                $form->handleRequest($request);

                if ($form->isSubmitted() && $form->isValid()) {
                    $this->getDoctrine()->getManager()->flush();

                    return $this->redirectToRoute('post_index');
                }

                return $this->render('post/edit.html.twig', [
                    'post' => $post,
                    'form' => $form->createView(),
                ]);
            } else {
                return $this->redirectToRoute('post_index');
            }

        } else {
            return $this->redirectToRoute('app_login');
        }
    }

    /**
     * @Route("/{id}", name="post_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Post $post): Response
    {
        if($this->session->get('is_logged_in') == true)
        {
            if($this->session->get('user_id') == $post->getUserId()) {
                if ($this->isCsrfTokenValid('delete' . $post->getId(), $request->request->get('_token'))) {
                    $entityManager = $this->getDoctrine()->getManager();
                    $entityManager->remove($post);
                    $entityManager->flush();
                }
            }

            return $this->redirectToRoute('post_index');
        } else {
            return $this->redirectToRoute('app_login');
        }
    }
}

templates/post/_delete_form.html.twig
<form name="delete-post-form" method="post" action="{{ path('post_delete', {'id': post.id}) }}"
    onsubmit="return confirm('Are you sure you want to delete post?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button name="delete-post-btn" type="submit" class="btn btn-link action-lnk"><i class="material-icons delete-icon-adj">delete</i></button>
</form>

templates/post/_form.html.twig
<div id="post-form-container">
    {{ form_start(form) }}
        {{ form_errors(form) }}
        {{ form_widget(form) }}
        <hr>
        <button id="save-post-btn" name="save-post-btn" type="submit" class="btn btn-primary btn-lg">
            {{ button_label|default('add') }}
        </button>
        <button id="clear-post-btn" name="clear-post-btn" type="reset" class="btn btn-light btn-lg">clear</button>
    {{ form_end(form) }}
</div>

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Post: {{ post.id }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <h2 class="h2-mt-10"><i class="material-icons">edit</i> Edit Post: {{ post.id }}</h2>
            <hr>
            {{ include('post/_form.html.twig', {'button_label': 'edit'}) }}
            <a class="pull-right btn btn-secondary" href="{{ path('post_index') }}"><< back to ledger</a>
        </div>
    </div>
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post Ledger{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
        {%  if app.user != null %}
            <h2 class="h2-mt-10"><i class="material-icons">comment</i> Post Ledger</h2>
            <hr>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th colspan="3">ACTION</th>
                        <th>ID</th>
                        <th>USER</th>
                        <th>TITLE</th>
                        <th>BODY <small class="alert alert-warning" style="padding:2px 4px">snippet</small></th>
                        <th>DATE</th>
                    </tr>
                </thead>
                <tbody>
                {% for post in posts %}
                    <tr>
                        {% if app.user.id == post.userId %}
                            <td class="action-lnk">{{ include('post/_delete_form.html.twig') }}</td>
                            <td class="action-lnk"><a href="{{ path('post_edit', {'id': post.id}) }}"><i class="material-icons">edit</i></a></td>
                        {% else %}
                            <td class="action-lnk"><a title="You are not allowed to delete post: {{ post.id }}" class="btn btn-link action-lnk delete-icon-adj"><i class="material-icons">delete_outline</i></a></td>
                            <td class="action-lnk"><a title="You are not allowed to edit post: {{ post.id }}"><i class="material-icons">edit</i></a></td>
                        {% endif %}
                        <td class="action-lnk"><a href="{{ path('post_show', {'id': post.id}) }}"><i class="material-icons">search</i></a></td>

                        <td>{{ post.id }}</td>
                        <td>{{ post.userId }}</td>
                        <td>{{ post.title }}</td>
                        <td><em>{{ post.body|slice(0, 32) }}...</em></td>
                        <td>{{ post.created }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="8" class="alert alert-warning text-center"><i class="material-icons">info_outline</i> There are no posts submitted.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <hr>
            <a class="pull-right btn btn-success" href="{{ path('post_new') }}">add post</a>
        {% endif %}

        {% if app.user == null %}
            <p class="alert alert-danger"><i class="material-icons">error_outline</i> This is a restricted page!  You must be logged in to view the ledger!</p>
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add Post{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <h2 class="h2-mt-10"><i class="material-icons">comment</i> Add Post</h2>
            <hr>
            {{ include('post/_form.html.twig') }}
            <a class="pull-right btn btn-secondary" href="{{ path('post_index') }}"><< back to ledger</a>
        </div>
    </div>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post Profile: {{ post.id }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <h2 class="h2-mt-10">Post Profile: {{ post.id }}</h2>
            <hr>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <td>{{ post.id }}</td>
                    </tr>
                    <tr>
                        <th>USER ID</th>
                        <td>{{ post.userId }}</td>
                    </tr>
                    <tr>
                        <th>DATE</th>
                        <td>{{ post.created }}</td>
                    </tr>
                    <tr>
                        <th>TITLE</th>
                        <td>{{ post.title }}</td>
                    </tr>
                    <tr>
                        <th>BODY</th>
                        <td>{{ post.body }}</td>
                    </tr>
                </tbody>
            </table>
            <hr>
            <a class="pull-right btn btn-secondary" href="{{ path('post_index') }}"><< back to ledger</a>
        </div>
    </div>
{% endblock %}